# Generated by Django 3.2 on 2022-10-17 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_game', models.CharField(max_length=124)),
                ('date_post', models.DateField()),
                ('review', models.TextField()),
            ],
            options={
                'db_table': 'post',
                'managed': True,
                'unique_together': {('name_game', 'date_post', 'review')},
            },
        ),
    ]
