# Generated by Django 4.1.1 on 2022-10-15 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=124)),
                ('name', models.CharField(max_length=124)),
                ('password', models.CharField(max_length=124)),
            ],
            options={
                'db_table': 'user',
                'managed': True,
                'unique_together': {('email', 'name', 'password')},
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_game', models.CharField(max_length=124)),
                ('date_post', models.DateField()),
                ('review', models.TextField()),
            ],
            options={
                'db_table': 'post',
                'managed': True,
                'unique_together': {('name_game', 'date_post', 'review')},
            },
        ),
    ]
